# Generated by Django 6.1 on 2026-08-29 11:14

import catalog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('commodity_name', models.CharField(max_length=150)),
                ('sub_category', models.CharField(blank=True, default='', max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('price_suggested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_GRADING', 'Pending Grading'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='config.vertical')),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('AI', 'AI'), ('VERIFIER', 'Verifier')], max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('attribute_scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_results', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='catalog.listing')),
            ],
            options={
                'db_table': 'grading_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=catalog.models.evidence_upload_path)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='catalog.listing')),
            ],
            options={
                'db_table': 'grading_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['vertical', 'status'], name='idx_listings_vert_status'),
        ),
    ]
