# Generated by Django 6.1 on 2026-08-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('grade_accuracy_score', models.FloatField(default=0.0)),
                ('fulfillment_score', models.FloatField(default=0.0)),
                ('payment_score', models.FloatField(default=0.0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_scores',
            },
        ),
    ]
