# Generated by Django 6.1.1 on 2026-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='search_radius_km',
            field=models.FloatField(default=100.0),
        ),
    ]
