# Generated by Django 6.1.1 on 2026-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_requirement_search_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='region',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
