# Generated by Django 6.1 on 2026-08-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('AGMARKNET', 'AGMARKNET'), ('ADMIN_ENTERED', 'Admin Entered'), ('CCI', 'CCI')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='config.vertical')),
            ],
            options={
                'db_table': 'price_points',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vertical', 'commodity', 'region', '-timestamp'], name='idx_price_points_lookup')],
            },
        ),
    ]
